# Generated by Django 4.0.5 on 2022-06-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='profile/images/')),
                ('bio', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='imageIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.TextField()),
                ('image_url', models.ImageField(upload_to='images/')),
                ('comments', models.TextField(blank=True)),
                ('likes', models.TextField(blank=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='instagra_app.userprofile')),
            ],
        ),
    ]
